### ISSUE TITLE
Retrieving an NSDate from a DateTime

### ISSUE THREAD

**Issue by haidalinda** [Haud/Kali#3]
While working with `DateTime` is more intuitive, sometimes you do need the `NSDate` representation at the end. Is is possible to retrieve an `NSDate` from a `DateTime`?

**Comment by Haud** [comment]
The `rawValue` of DateTime is the time interval since the epoch, so you can use taht to convert to an NSDate:

`NSDate(timeIntervalSince1970: dateTime.rawValue)`

**Comment by haidalinda** [comment]
awesome, thanks :+1:
